import { act, fireEvent, render, screen } from '@testing-library/react'
import { afterEach, beforeEach, expect, test, vi } from 'vitest'
import App from './App'
beforeEach(() => { window.history.replaceState(null, '', '/'); vi.useFakeTimers(); vi.setSystemTime(0) })
afterEach(() => vi.useRealTimers())
const click = (name: string) => fireEvent.click(screen.getByRole('button', { name }))
test('首頁沒有互動選項，選項二三在選單各自切換', () => {
  render(<App />)
  expect(screen.getByRole('heading', { level: 1 })).toHaveTextContent('David 的AI 學習筆記')
  expect(screen.queryByRole('button', { name: '選項二 · 綠' })).toBeNull()
  expect(screen.queryByRole('timer')).toBeNull()
  for (let i = 1; i <= 3; i++) { click('跟我打聲招呼'); expect(screen.getByText(`你已經按了 ${i} 次。`)).toBeVisible() }
  click('主選單')
  const option = screen.getByRole('button', { name: '選項二 · 綠' })
  for (const color of ['紅', '橙', '黃', '藍', '紫', '紅']) { fireEvent.click(option); expect(option).toHaveTextContent(`選項二 · ${color}`) }
  expect(screen.getByRole('button', { name: '選項三 · 綠' })).toBeVisible()
  expect(screen.queryByRole('button', { name: /選項一/ })).toBeNull()
})
test('選單關閉及番茄鐘頁切換不重置倒數', () => {
  render(<App />)
  click('主選單')
  fireEvent.keyDown(document, { key: 'Escape' })
  expect(screen.getByRole('button', { name: '主選單' })).toHaveFocus()
  click('主選單')
  fireEvent.click(screen.getByRole('heading', { level: 1 }))
  expect(screen.getByRole('button', { name: '主選單' })).toHaveAttribute('aria-expanded', 'false')
  click('主選單'); click('番茄鐘')
  expect(screen.getByRole('heading', { name: '番茄鐘' })).toHaveFocus()
  expect(screen.queryByRole('heading', { level: 1 })).toBeNull()
  expect(screen.getByRole('timer')).toHaveTextContent('30:00')
  click('開始')
  click('主選單'); fireEvent.click(screen.getByRole('link', { name: '學習首頁' }))
  click('跟我打聲招呼')
  act(() => vi.advanceTimersByTime(2000))
  click('主選單'); click('選項二 · 綠'); click('番茄鐘')
  expect(screen.getByRole('timer')).toHaveTextContent('29:58')
  act(() => vi.advanceTimersByTime(1000))
  expect(screen.getByRole('timer')).toHaveTextContent('29:57')
})
test('番茄鐘網址可直接載入，瀏覽器返回首頁會切換內容', () => {
  window.history.replaceState(null, '', '/#pomodoro')
  render(<App />)
  expect(screen.getByRole('timer')).toHaveTextContent('30:00')
  act(() => { window.history.replaceState(null, '', '/#home'); window.dispatchEvent(new Event('hashchange')) })
  expect(screen.getByRole('heading', { level: 1 })).toBeVisible()
  expect(screen.queryByRole('timer')).toBeNull()
})
